server:
  port: 8888

spring:
  application:
    name: nebulamall-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Third Party Service - MinIO and other third-party services (more specific, should be first)
        - id: third_party_route
          uri: lb://Nebula-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /thirdparty/$\{segment}
        
        # Admin Service (captcha, login, and admin APIs) - Renren-Fast
        - id: admin_route
          uri: http://localhost:8080
          predicates: 
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}
  
