server:
  port: 8888

spring:
  application:
    name: nebulamall-gateway
  cloud:
    gateway:
      routes:
        # Product Service
        - id: product_route
          uri: lb://nebulamall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # Coupon Service
        - id: coupon_route
          uri: lb://nebulamall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # Member Service
        - id: member_route
          uri: lb://nebulamall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # Order Service
        - id: order_route
          uri: lb://nebulamall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # Ware Service
        - id: ware_route
          uri: lb://nebulamall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
