server:
  port: 10002

spring:
  application:
    name: nebulamall-coupon
  # 临时数据源配置（可被 Nacos 的 datasource.yml 覆盖）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nebulamall-sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


nebulamall:
  user:
    name: zyz1
    age: 18